Repository 02shreyansh/CODSOFT, pull requests merged in 2024-01, with the labels that each got.

#14 Add the Proper readme.md file in it #9
  README.md
Labels: documentation, JWOC, Easy

#18 Enrollment page created
  Landing page/enroll.html
  Landing page/index.html
Labels: enhancement, good first issue, JWOC, Easy

#22 Loader
  Landing page/index.html
  Landing page/logoo.webp
  Landing page/script.js
  Landing page/style.css
Labels: enhancement, JWOC, Medium

#23 feat: Animate (class=heroright ,content)
  Landing page/script.js
Labels: enhancement, good first issue, JWOC, Medium

#27 bug: Heroright animation not visible
  Landing page/script.js
Labels: BUG, JWOC, Medium

#29 fix: Remove unintended drag functionality for image
  Landing page/index.html
Labels: enhancement, JWOC, Medium

#32 navbar
  Landing page/index.html
  Landing page/saturn.png
  Landing page/style.css
Labels: BUG, JWOC, Easy

#35 added rating page
  Landing page/daksh.jpg
  Landing page/feedback.css
  Landing page/feedback.html
  Landing page/index.html
Labels: JWOC, Easy

#36 feat: Add footer section
  Landing page/index.html
  Landing page/style.css
Labels: documentation, JWOC, Medium

#25 fix: ReadMe fixes
  README.md
Labels: JWOC, Easy

#39 Added the navbar for login and enroll page
  .vscode/settings.json
  Landing page/enroll.html
  Landing page/index.html
  Landing page/login.css
  Landing page/login.html
  Landing page/style.css
Labels: JWOC, Medium

#40 #Add planets and Blog page (issue #13) completed
  Landing page/blog.css
  Landing page/blog.html
  Landing page/index.html
  Landing page/planet.css
  Landing page/planet.html
  Landing page/planet.js
Labels: enhancement, good first issue, JWOC, Medium

#44 Added faq and improve the footer
  Landing page/index.html
  Landing page/style.css
Labels: JWOC, Medium

#43 added login with google
  Landing page/login.html
  Landing page/new.html
Labels: JWOC, Medium

#54 Created a footer in blog page
  Landing page/blog.css
  Landing page/blog.html
Labels: JWOC, Medium

#55 feat: Add about page
  Landing page/about-background.jpg
  Landing page/about.html
  Landing page/index.html
  Landing page/style.css
Labels: JWOC, Medium

#61 fix: enroll button
  Landing page/blog.css
  Landing page/blog.html
  Landing page/enroll.html
  Landing page/feedback.css
  Landing page/feedback.html
  Landing page/index.html
  Landing page/login.css
  Landing page/login.html
  Landing page/planet.css
  Landing page/planet.html
  Landing page/style.css
Labels: JWOC, Medium

#63 Added favicon icon to all pages
  Landing page/blog.html
  Landing page/enroll.html
  Landing page/feedback.html
  Landing page/login.html
  Landing page/new.html
  Landing page/planet.html
Labels: JWOC, Easy

#65 Added the footer to login and enroll page
  Landing page/enroll.html
  Landing page/login.css
  Landing page/login.html
Labels: JWOC, Medium

#66 #contact page (Issue #52) completed
  Landing page/contact.js
  Landing page/img/email.png
  Landing page/img/location.png
  Landing page/img/phone.png
  Landing page/img/shape.png
  Landing page/index.html
  Landing page/style.css
Labels: JWOC, Medium

#69 Created scroll back to top button
  Landing page/blog.css
  Landing page/blog.html
  Landing page/enroll.html
  Landing page/index.html
  Landing page/login.html
  Landing page/scroll.js
  Landing page/style.css
Labels: JWOC, Medium

#68 fix: logo
  Landing page/blog.css
  Landing page/blog.html
  Landing page/enroll.html
  Landing page/feedback.css
  Landing page/feedback.html
  Landing page/index.html
  Landing page/login.css
  Landing page/login.html
  Landing page/planet.css
  Landing page/planet.html
  Landing page/style.css
  Landing page/trailer.html
Labels: JWOC, Easy

#71 #Add ticket booking page completed (Issue #8)
  Landing page/index.html
  Landing page/planet.html
  Landing page/ticket.html
Labels: enhancement, JWOC, hard

#74 added apod
  Landing page/apod.css
  Landing page/apod.html
  Landing page/apod.js
  Landing page/index.html
Labels: JWOC, hard
