Repository 02shreyansh/CODSOFT, pull requests merged in 2024-02, with the labels that each got.

#76 added mars images feature
  Landing page/apod.js
  Landing page/img/mars.png
  Landing page/index.html
  Landing page/mars.html
Labels: JWOC, hard

#78 fixed the style of the enrollment page
  Landing page/enroll.html
Labels: JWOC, Medium

#80 login page rebuilt
  Landing page/img/Screenshot 2024-02-01 021751.png
  Landing page/login.html
Labels: JWOC, Medium

#83 functional contact us
  Landing page/index.html
  Landing page/index.js
Labels: JWOC, hard

#85 add blog : james webb telescope
  Landing page/blog.css
  Landing page/blog.html
  Landing page/img/jwst-spacecraftpotentialtargetsmontageflip-1200px-4-jpg.webp
Labels: JWOC, hard

#87 add annular eclipse
  Landing page/blog.css
  Landing page/blog.html
Labels: JWOC, Medium

#89 Add international space station card in blogs
  Landing page/blog.css
  Landing page/blog.html
Labels: JWOC, Medium

#91 add links in footer
  Landing page/enroll.html
Labels: JWOC, Medium

#93 add virgin galactic
  Landing page/blog.css
  Landing page/blog.html
Labels: JWOC, Medium

#94 added trailer
  Landing page/trailer.html
Labels: JWOC, hard

#101 added wormhole
  Landing page/blog.css
  Landing page/blog.html
Labels: JWOC, Medium

#100 fixed distortion on rate us page
  Landing page/feedback.css
  Landing page/feedback.html
Labels: JWOC, Medium

#104 add pragyan rover
  Landing page/blog.css
  Landing page/blog.html
Labels: JWOC, Medium

#105 Added blog on Small satellite launch vehicle
  Landing page/blog.css
  Landing page/blog.html
Labels: JWOC, Medium

#106 add menu
  Landing page/index.html
Labels: JWOC, hard

#107 dedicated Wormhole blog page
  Landing page/blog.html
  Landing page/img/ggg.jpg.webp
  Landing page/worm_blog.html
Labels: JWOC, hard

#113 Fixed Footer of Blog Page
  Landing page/blog.css
  Landing page/blog.html
Labels: JWOC, Medium

#114 Aditya L1 blog page added
  Landing page/Aditya_L1_blog.html
  Landing page/blog.html
Labels: JWOC, Medium

#119 fix martian
  Landing page/blog.css
Labels: JWOC, Medium

#120 Fixed enroll page input
  Landing page/enroll.html
Labels: JWOC, Medium

#121 Fixed change of planet name with mis-click
  Landing page/index.html
  Landing page/script.js
Labels: JWOC, Medium

#125 Added menu to all the pages
  Landing page/Aditya_L1_blog.html
  Landing page/apod.css
  Landing page/apod.html
  Landing page/blog.css
  Landing page/blog.html
  Landing page/chandrayaan.html
  Landing page/enroll.html
  Landing page/feedback.css
  Landing page/feedback.html
  Landing page/mars.html
  Landing page/planet.css
  Landing page/planet.html
  Landing page/ticket.html
  Landing page/trailer.html
  Landing page/worm_blog.html
Labels: JWOC, hard

#126 Blog page revamp and fix
  Landing page/blog.html
Labels: JWOC, hard

#133 Add scroll back to top button to all the pages
  Landing page/apod.css
  Landing page/apod.html
  Landing page/blog.css
  Landing page/blog.html
  Landing page/chandrayaan.html
  Landing page/mars.html
  Landing page/ticket.html
  Landing page/trailer.html
  Landing page/worm_blog.html
Labels: JWOC, hard

#136 Annular Blog Added
  Landing page/AnnularEclipse_blog.html
  Landing page/blog.html
Labels: JWOC, Medium

#137 Pragyan Rover BlogPage
  Landing page/blog.html
  Landing page/pragyan.html
Labels: JWOC, Medium

#138 Virgin Galactic Blog
  Landing page/blog.html
  Landing page/virginGalactic.html
Labels: JWOC, Medium

#139 add blogPage for Gaganyaan
  Landing page/blog.html
  Landing page/gaganyan.html
Labels: JWOC, Medium

#142 fix menu in planets page
  Landing page/planet.html
Labels: JWOC, Medium

#143 Added Blog on James Webb Space Telescope
  Landing page/JWST_blog.html
  Landing page/blog.html
Labels: JWOC, Medium

#135 Create a new Animated Enrollment Form !
  Landing page/index.html
  Landing page/newEnroll.css
  Landing page/newEnroll.html
Labels: JWOC, Medium

#147 Craeted a customised scroll bar and added to all the pages
  Landing page/apod.css
  Landing page/blog.css
  Landing page/enroll.html
  Landing page/index.html
  Landing page/mars.html
  Landing page/new.html
  Landing page/ticket.html
  Landing page/trailer.html
Labels: JWOC, hard

#148 Added Blog on Sputnik 1
  Landing page/Sputnik_blog.html
  Landing page/blog.html
Labels: JWOC, Medium

#149 Added a Blog on International Space Station
  Landing page/ISS_blog.html
  Landing page/blog.html
Labels: JWOC, Medium

#167 Improve the Rate Us page
  Landing page/feedback.html
  Landing page/newFeed.css
Labels: JWOC, Medium

#163 Added Create account page
  Landing page/create-account.html
  Landing page/login.html
Labels: JWOC, Medium

#158 fix broken links
  Landing page/feedback.html
Labels: JWOC, Easy

#157 fix sputnik card
  Landing page/blog.html
Labels: JWOC, Medium

#156 sslv blogpage
  Landing page/blog.html
  Landing page/sslv.html
Labels: JWOC, Medium

#168 Add Animation to Blog Page
  Landing page/blog.html
Labels: JWOC, Medium

#170 Improved Footer & Header of About section
  Landing page/about.html
Labels: JWOC, Medium

#169 Added Footer & Header in Login page
  Landing page/login.html
Labels: JWOC, Medium

#179 fix links in about us
  Landing page/about.html
Labels: JWOC, Easy

#180 fix menu in enroll page
  Landing page/newEnroll.css
Labels: JWOC, Medium

#181 documentary page
  Landing page/documentary.html
Labels: JWOC, hard

#187 Add hover effect to blog container #186
  Landing page/blog.html
Labels: JWOC, Medium

#189 fix menu in trailer
  Landing page/ticket.html
Labels: JWOC, Easy

#190 add documentary on cosmophobia
  Landing page/documentary.html
Labels: JWOC, Medium

#193 blackhole blog
  Landing page/blackhole.html
  Landing page/blog.html
Labels: JWOC, Medium

#192 Added animations to all the pages
  Landing page/Aditya_L1_blog.html
  Landing page/about.html
  Landing page/apod.html
  Landing page/feedback.html
  Landing page/login.html
  Landing page/mars.html
  Landing page/planet.html
  Landing page/ticket.html
  Landing page/trailer.html
Labels: JWOC, hard

#195 spacetime blog
  Landing page/documentary.html
Labels: JWOC, Medium

#196 Modify the rate us page
  Landing page/feedback.html
  Landing page/newFeed.css
Labels: JWOC, Medium

#200 add space mystery documentary
  Landing page/documentary.html
Labels: JWOC, Medium

#201 fix duplicate images
  Landing page/blog.html
Labels: JWOC, Medium

#207 Added Customized scrollbar in about us page
  Landing page/about.html
Labels: JWOC, Medium

#213 added documentary on milky way
  Landing page/documentary.html
Labels: JWOC, Medium

#214 Adopt New File Structure #210
  .vscode/settings.json
  Landing page/Asset/css/apod.css
  Landing page/Asset/css/blog.css
  Landing page/Asset/css/feedback.css
  Landing page/Asset/css/login.css
  Landing page/Asset/css/newEnroll.css
  Landing page/Asset/css/newFeed.css
  Landing page/Asset/css/planet.css
  Landing page/Asset/css/style.css
  Landing page/Asset/images/Screenshot 2024-02-01 021751.png
  Landing page/Asset/images/about-background.jpg
  Landing page/Asset/images/bg.jpg
  Landing page/Asset/images/daksh.jpg
  Landing page/Asset/images/email.png
  Landing page/Asset/images/ggg.jpg.webp
  Landing page/Asset/images/jwst-spacecraftpotentialtargetsmontageflip-1200px-4-jpg.webp
  Landing page/Asset/images/location.png
  Landing page/Asset/images/logoo.webp
  Landing page/Asset/images/mars.png
  Landing page/Asset/images/phone.png
  Landing page/Asset/images/saturn.png
  Landing page/Asset/images/shape.png
  Landing page/Asset/pages/Blog/Aditya_L1_blog.html
  Landing page/Asset/pages/Blog/AnnularEclipse_blog.html
  Landing page/Asset/pages/Blog/ISS_blog.html
  Landing page/Asset/pages/Blog/JWST_blog.html
  Landing page/Asset/pages/Blog/Sputnik_blog.html
  Landing page/Asset/pages/Blog/blackhole.html
  Landing page/Asset/pages/Blog/chandrayaan.html
  Landing page/Asset/pages/Blog/gaganyan.html
  Landing page/Asset/pages/Blog/pragyan.html
  Landing page/Asset/pages/Blog/sslv.html
  Landing page/Asset/pages/Blog/virginGalactic.html
  Landing page/Asset/pages/Blog/worm_blog.html
  Landing page/Asset/pages/about.html
  Landing page/Asset/pages/apod.html
  Landing page/Asset/pages/blog.html
  Landing page/Asset/pages/create-account.html
  Landing page/Asset/pages/documentary.html
  Landing page/Asset/pages/enroll.html
  Landing page/Asset/pages/feedback.html
  Landing page/Asset/pages/login.html
  Landing page/Asset/pages/mars.html
  Landing page/Asset/pages/new.html
  Landing page/Asset/pages/newEnroll.html
  Landing page/Asset/pages/planet.html
  Landing page/Asset/pages/ticket.html
  Landing page/Asset/pages/trailer.html
  Landing page/Asset/script/apod.js
  Landing page/Asset/script/contact.js
  Landing page/Asset/script/index.js
  Landing page/Asset/script/planet.js
  Landing page/Asset/script/script.js
  Landing page/Asset/script/scroll.js
  Landing page/ISS_blog.html
  Landing page/index.html
Labels: JWOC, hard

#212 added nasa media search engine
  Landing page/index.html
  Landing page/searchEngine.html
Labels: JWOC, hard

#220 #215 FIxed the page
  Landing page/css/searchengine.css
  Landing page/pages/searchEngine.html
Labels: JWOC, Medium

#222 Add search bar to search blog #211
  Landing page/pages/blog.html
Labels: JWOC, Medium

#226 add chatbot
  Landing page/index.html
  Landing page/script/scroll.js
Labels: JWOC, hard

#224 Added customised scrollbar to all the pages
  Landing page/pages/Blog/Aditya_L1_blog.html
  Landing page/pages/Blog/AnnularEclipse_blog.html
  Landing page/pages/Blog/ISS_blog.html
  Landing page/pages/Blog/JWST_blog.html
  Landing page/pages/Blog/Sputnik_blog.html
  Landing page/pages/Blog/blackhole.html
  Landing page/pages/Blog/chandrayaan.html
  Landing page/pages/Blog/gaganyan.html
  Landing page/pages/Blog/pragyan.html
  Landing page/pages/Blog/sslv.html
  Landing page/pages/Blog/virginGalactic.html
  Landing page/pages/Blog/worm_blog.html
Labels: JWOC, hard

#227 fixed all menu's aligment
  Landing page/pages/about.html
  Landing page/pages/apod.html
  Landing page/pages/blog.html
  Landing page/pages/documentary.html
  Landing page/pages/enroll.html
  Landing page/pages/feedback.html
  Landing page/pages/login.html
  Landing page/pages/mars.html
  Landing page/pages/newEnroll.html
  Landing page/pages/planet.html
  Landing page/pages/searchEngine.html
  Landing page/pages/ticket.html
  Landing page/pages/trailer.html
Labels: JWOC, hard

#230 #229 Added this features
  Landing page/pages/Blog/AnnularEclipse_blog.html
  Landing page/pages/Blog/ISS_blog.html
  Landing page/pages/Blog/Sputnik_blog.html
  Landing page/pages/Blog/blackhole.html
  Landing page/pages/Blog/chandrayaan.html
  Landing page/pages/Blog/gaganyan.html
  Landing page/pages/Blog/pragyan.html
  Landing page/pages/Blog/sslv.html
  Landing page/pages/Blog/virginGalactic.html
  Landing page/pages/Blog/worm_blog.html
Labels: JWOC, hard

#231 Add ISS Documentary
  Landing page/pages/documentary.html
Labels: JWOC, Medium

#232 add Alien Documentary
  Landing page/pages/documentary.html
Labels: JWOC, Medium

#233 fixed footer links across all pages
  Landing page/index.html
  Landing page/pages/about.html
  Landing page/pages/apod.html
  Landing page/pages/blog.html
  Landing page/pages/documentary.html
  Landing page/pages/enroll.html
  Landing page/pages/feedback.html
  Landing page/pages/login.html
  Landing page/pages/mars.html
  Landing page/pages/newEnroll.html
  Landing page/pages/searchEngine.html
  Landing page/pages/ticket.html
  Landing page/pages/trailer.html
Labels: JWOC, Medium

#240 fixed distorted cards
  Landing page/pages/documentary.html
Labels: JWOC, Easy

#241 documentary on space Anomalies
  Landing page/pages/documentary.html
Labels: JWOC, Medium

#242 Add documentary on Andromeda
  Landing page/pages/documentary.html
Labels: JWOC, Medium

#243 added chatbot on all pages
  Landing page/pages/about.html
  Landing page/pages/apod.html
  Landing page/pages/blog.html
  Landing page/pages/documentary.html
  Landing page/pages/feedback.html
  Landing page/pages/login.html
  Landing page/pages/mars.html
  Landing page/pages/new.html
  Landing page/pages/newEnroll.html
  Landing page/pages/planet.html
  Landing page/pages/searchEngine.html
  Landing page/pages/ticket.html
  Landing page/pages/trailer.html
Labels: JWOC, hard

#244 added links in contact us form
  Landing page/index.html
Labels: JWOC, Easy
